baseURL = "https://utkarshverma.me"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Utkarsh Verma"
theme = "dream-theme"

copyright = ""
googleAnalytics = "UA-112332904-3"

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = false

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Utkarsh Verma"
  description = "A hub for my works."
  avatar = "/images/avatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."
  customCSS = [""]
  customJS  = [""]
  favicon = "/images/favicon.ico"
  
#Background Settings
  enableColourBG= false
  bgBlur = 0.5
  bgImage = "/images/bg1.jpeg"
  bgList = ["/images/bg1.jpeg", "/images/bg2.jpeg", "/images/bg3.jpeg", "/images/bg4.jpeg", "/images/bg5.jpeg", "/images/bg6.jpeg", "/images/bg7.jpeg"]
  
# Post-displaying Settings  
  enablePost = false
  enableTags = false
  enableCategories = false
  postsPerPage = 4

  #Enable Twitter Emoji
  twitterEmoji=true


#Socail Links
  email = "utkarshverma@protonmail.com"
  github = "UtkarshVerma"
  linkedin = ""
  codepen = ""
  stackoverflow = ""
  BlogLink = "https://blog.utkarshverma.me"
  medium = "utkarsh.naveen"
  reddit = "UtkarshVerma_"
  twitter = "UtkarshVerma_" 
  siteStartYear = 2018
 
