baseURL = "https://utkarshverma.me"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Utkarsh Verma"
theme = "dream-theme"

copyright = ""
googleAnalytics = "UA-112332904-3"

disqusShortname = ""

enableRobotsTXT = true

hasCJKLanguage = false

[params]
  author = "Utkarsh Verma"
  description = "A hub for my works."
  avatar = "/img/avatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."
  customCSS = ["home.css"]
  customJS  = [""]

  
  email = "utkarshverma@protonmail.com"
  github = "UtkarshVerma"
  linkedin = ""
  codepen = ""
  stackoverflow = ""
  BlogLink = "https://blog.utkarshverma.me"
  medium = "utkarsh.naveen"
  reddit = "UtkarshVerma_"
  twitter = "UtkarshVerma_" 
  siteStartYear = 2018
 