baseURL = "https://utkarshverma.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "UtkarshVerma's Site"
theme = "dream-plus"

googleAnalytics = "UA-112332904-3"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Utkarsh Verma"
  description = "A hub for my works."
  avatar = "/images/avatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."

  favicon = "images/favicon.ico"
  
#Background Settings
  enableColorBG = true
  
#Post-displaying Settings
  enableTags = false
  enableCategories = false

#Cards or posts shown per page
  itemsPerPage = 4

#Set whether you're hosting "cards" or "post"
  contentType = "cards"

  #Enable Twitter Emoji
  twitterEmoji=true

[social]
  email = "utkarshverma@pm.me"
  github = "UtkarshVerma"
  stackoverflow = "9271608/utkarsh-verma"
  medium = "UtkarshVerma_"
  twitter = "UtkarshVerma_" 
  siteStartYear = 2018
