baseURL = "https://utkarshverma.me"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "UtkarshVerma's Site"
theme = "dream-plus"

copyright = ""
googleAnalytics = "UA-112332904-3"

disqusShortname = "UtkarshVermaBlog"

enableRobotsTXT = true

hasCJKLanguage = false

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "Utkarsh Verma"
  description = "A hub for my works."
  avatar = "/images/avatar.jpg"
  motto = "A keen maker, programmer and an Instructables author."
  enableToc = true
  enableShareCard = true
 
  #Use your external CSS/JS files with this theme by placing the location of the file within the list. For example: "js/twemoji.js" 
  customCSS = [""]
  customJS  = [""]
  favicon = "/images/favicon.ico"
  
  #Shorte.st Settings
  enableShortest = false
  
#Background Settings
  enableColorBG = false
  bgBlur = 3
  bgImage = "/images/bg1.jpeg"
  bgList = ["/images/bg1.jpeg", "/images/bg2.jpeg", "/images/bg3.jpeg", "/images/bg4.jpeg", "/images/bg5.jpeg", "/images/bg6.jpeg", "/images/bg7.jpeg"]
  
#Post-displaying Settings
  enableTags = false
  enableCategories = false

#Cards or posts shown per page
  itemsPerPage = 4

#Set whether you're hosting "cards" or "post"
  contentType = "cards"

#Enable/disable post/card  dimming effect
  enableDimmer = true

#Heading for 404 Page
  error404 = "Error 404: Page Not Found"

  #Enable Twitter Emoji
  twitterEmoji=true

#Heading for the About page
  aboutHeader = "So, Who Am I?"

#Link to your blog
  BlogLink = "https://blog.utkarshverma.me"

#Social Links
  email = "utkarshverma@protonmail.com"
  github = "UtkarshVerma"
  linkedin = ""
  codepen = ""
  stackoverflow = "9271608/utkarsh-verma"
  medium = "UtkarshVerma_"
  twitter = "UtkarshVerma_" 
  siteStartYear = 2018
 
